//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoeyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int IDcalificacion { get; set; }
        public Nullable<int> IDProducto { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Calificacion1 { get; set; }
    
        public virtual Producto Productoes { get; set; }
    }
}
