//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoeyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int IDCarrito { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public Nullable<int> IDProducto { get; set; }
        public Nullable<int> IDInventario { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Cliente Clientes { get; set; }
        public virtual Inventario Inventarios { get; set; }
        public virtual Producto Productoes { get; set; }
    }
}
