//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoeyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesOrden
    {
        public int IDDetalleOrden { get; set; }
        public Nullable<int> IDOrden { get; set; }
        public Nullable<int> IDProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> IDInventario { get; set; }
    
        public virtual Inventario Inventarios { get; set; }
        public virtual Producto Productoes { get; set; }
        public virtual DetallesOrden DetallesOrdens1 { get; set; }
        public virtual DetallesOrden DetallesOrdens2 { get; set; }
        public virtual Orden Ordens { get; set; }
    }
}
